version: '3.9'

services:
  da1:
      image: antitree/private-tor:0.3.4
      #expose:
      #  - "7000"
      #  - "9030"
      environment:
        ROLE: DA
      volumes:
        ## Needed to keep track of other nodes
        - ./tor:/tor
  da2:
      image: antitree/private-tor:0.3.4
      #expose:
      #  - "7000"
      #  - "9030"
      environment:
        ROLE: DA
      volumes:
        ## Needed to keep track of other nodes
        - ./tor:/tor
  da3:
      image: antitree/private-tor:0.3.4
      #expose:
      #  - "7000"
      #  - "9030"
      environment:
        ROLE: DA
      volumes:
        ## Needed to keep track of other nodes
        - ./tor:/tor
  relay:
      image: antitree/private-tor:0.3.4
      #expose:
      #  - "7000"
      #  - "9030"
      deploy:
        replicas: 5
      environment:
        ROLE: RELAY
      volumes:
        - ./tor:/tor
      depends_on:
        # Make sure the DA's are already up
        - da1
        - da2
        - da3
  exit:
      image: antitree/private-tor:0.3.4
      #expose:
      #  - "7000"
      #  - "9030"
      environment:
        ROLE: EXIT
      deploy:
        replicas: 3
      volumes:
        - ./tor:/tor
      depends_on:
        # Make sure the DA's are already up
        - da1
        - da2
        - da3
  client:
      ports:
        # Setups a listener on host machine
        - "9050:9050"
        - "9051:9051"
      volumes:
        - ./tor:/tor
        - aesmd-socket:/var/run/aesmd
        - ./:/private-tor-network
      environment:
        ROLE: CLIENT
      depends_on:
        - aesmd
        - da1
        - da2
        - da3
      build:
        context: ./
        dockerfile: Dockerfile
      env_file: .env
      extends:
        file: sgx-driver.yml
        service: ${SGX_DRIVER}-enclave-devices
  hs:
      image: antitree/private-tor:0.3.4
      #expose:
      #  - "80"
      environment:
        ROLE: HS
        # This will create a hidden service that points to
        # the service "web" which is runing nginx. You can
        # change this to whatever ip or hostname you want
        TOR_HS_PORT: "80"
        TOR_HS_ADDR: "web"
      volumes:
        - ./tor:/tor
      depends_on:
        - da1
        - da2
        - da3
      links:
        - web
  web:
      image: nginx
      #expose:
      #  - "80"
  aesmd:
      image: ghcr.io/initc3/sgx-aesm:2.19-buster-81eb0d3
      volumes:
        - aesmd-socket:/var/run/aesmd
      # NOTE set SGX_DRIVER in your .env file to "oot" or "inkernel"
      # see README for more details
      extends:
        file: sgx-driver.yml
        service: ${SGX_DRIVER}-aesmd-devices

volumes:
  aesmd-socket:
    driver: local
    driver_opts:
      type: "tmpfs"
      device: "tmpfs"
      o: "rw"


